# Generated by Django 4.2.8 on 2023-12-31 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="tweetdata", options={"managed": False},),
    ]
