# Generated by Django 4.2.8 on 2023-12-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_tweetdata_options"),
    ]

    operations = [
        migrations.AlterModelTable(name="tweetdata", table="westernRecRm",),
    ]
