# Generated by Django 4.2.8 on 2023-12-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_tweetdata_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="tweetdata", table="tweetData",),
    ]
